name: Duolingo README Stats Action

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    name: Update readme with your duolingo stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: centrumek/duolingo-readme-stats@main
        with:
          SHOW_STREAK_TIMEZONE: false
          FILE_NAME: readme.md
          DUOLINGO_USER_ID: ${{ vars.DUOLINGO_USER_ID }}
          ADVANCED_TOKEN_JWT: ${{ vars.DUOLINGO_TOKEN_JWT }}
          COMMIT_MSG: 'Update duolingo stats'
          COMMIT_USERNAME: mayannaoliveira
