name: Duolingo README Stats Action

# GitHub Actions documentation: https://docs.github.com/en/actions
# GitHub Marketplace Actions: https://github.com/marketplace?type=actions

on:
  schedule:
    - cron: "21 */6 * * *" # https://crontab.guru
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with duolingo stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: centrumek/duolingo-readme-stats@main
        with:
          SHOW_STREAK_TIMEZONE: true
          DUOLINGO_USER_ID: mayannait
          COMMIT_EMAIL: mayannait@gmail.com
          COMMIT_MSG: 'chore(duolingo): [NO-REF] Update duolingo stats 💬'
          COMMIT_USERNAME: mayannaoliveira
