name: Update Credly Badges
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update README with Credly badges
    runs-on: ubuntu-latest  
    # Add these permissions
    permissions:
      contents: write  # Needed to push changes to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for some credential operations
      - name: Update Badges in README
        uses: jd-35656/readme-credly-badges@v1
        with:
          credly_username: "mayannaoliveira"
          badge_size: "100x100"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_branch: "master"
          readme_file: "credly-badges.md"
          commit_message: "Update Credly badges"
